site_name: Alejandra's WizeOs Profile
nav:
  - Home: index.md
  - Education: education.md
  - Experience: experience.md
  - Skills: skills.md
  - Past Work: past-work.md
  

theme:
  name: material
  palette:
    primary: black
    accent: indigo
  logo: images/wizeline_isotype.png